on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Run Zebra Tests
      uses: ./
      with:
        test-plan-path: ./Platform
      
        
  
