name: Build and Run Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-run-docker:
    runs-on: self-hosted

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (required for multi-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t newtest22-runner .

      # Run the Docker container
      - name: Run Docker Container
        run: |
          docker run --name newtest22-container -p 7993:7993 newtest22-runner

      # Check logs (for debugging purposes)
      - name: Fetch Container Logs
        run: |
          docker logs newtest22-container

      # Stop and Remove the container after completion
      - name: Cleanup
        run: |
          docker stop newtest22-container
          docker rm newtest22-container
