name: Build and Run Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-run-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t newtest15-runner .

      # Run the Docker container
      - name: Run Docker Container
        run: |
          docker run --name newtest15-container -p 7993:7993 newtest15-runner

      # Check logs (for debugging purposes)
      - name: Fetch Container Logs
        run: |
          docker logs newtest-container

      # Stop and Remove the container after completion
      - name: Cleanup
        run: |
          docker stop newtest15-container
          docker rm newtest15-container
